from typing import List, Dict

class Emitter:
    def __init__(self):
        self.text: List[str] = []
        self.data: List[str] = []
        self.string_pool: Dict[str, str] = {}
        self.label_counter = 0

    def unique_label(self, base: str = "L") -> str:
        self.label_counter += 1
        return f"{base}{self.label_counter}"

    def emit(self, line: str):
        self.text.append(line)

    def label(self, name: str):
        self.text.append(f"{name}:")

    def add_string(self, s: str) -> str:
        if s in self.string_pool:
            return self.string_pool[s]
        label = f"STR_{len(self.string_pool)}"
        # DOS function 09h expects '$' terminated strings
        escaped = s.replace('$', '$$')
        self.data.append(f"{label} db '{escaped}','$'")
        self.string_pool[s] = label
        return label

    def render(self) -> str:
        out: List[str] = []
        out.append("; generated by QuinLang compiler")
        out.append("org 0x100")
        out.append("%include 'runtime/runtime.inc'")
        out.append("section .text")
        out.extend(self.text)
        out.append("section .data")
        out.extend(self.data)
        return "\n".join(out)
